In [4]:
# -*-coding:utf-8-*-
from collections import Counter  
import jieba
      
# jieba.load_userdict('userdict.txt')  
# 创建停用词list  
def stopwordslist(filepath):  
    stopwords = [line.strip() for line in open(filepath, 'r').readlines()]  
    return stopwords  
      
      
# 对句子进行分词  
def seg_sentence(sentence):  
    sentence_seged = jieba.cut(sentence.strip())  
    stopwords = stopwordslist('stopwords(ch).txt')  # 这里加载停用词的路径  
    outstr = ''  
    for word in sentence_seged:  
        if word not in stopwords:  
            if word != '\t':
                outstr += word  
                outstr += " "  
    return outstr  
      
# 分词并且计算频率
def count_frenquent(i):
    inputs = open('neg.'+ str(i) +'.txt', 'r',encoding='utf-8') #加载要处理的文件的路径  
    outputs = open('neg.'+ str(i) +'.withoutstop.txt', 'w',encoding='utf-8') #加载处理后的文件路径
    for line in inputs:  
        line_seg = seg_sentence(line)  # 这里的返回值是字符串  
        outputs.write(line_seg)
    outputs.close()  
    inputs.close()  

    # WordCount  
    with open('neg.'+str(i)+'.withoutstop.txt', 'r',encoding='utf-8') as fr: #读入已经去除停用词的文件  
          data = jieba.cut(fr.read())  
    
    data = dict(Counter(data)) 
    
    with open('neg.'+str(i)+'.count.txt', 'w',encoding='utf-8') as fw: #读入存储wordcount的文件路径  
        for k,v in data.items():  
            fw.write('%s,%d\n' % (k, v))

In [6]:
count_frenquent(0)

In [5]:
if __name__ =="__main__":
    for i in range(11):
        count_frenquent(i)

In [4]:
sum_list = 0
for i in range(11):
    inputs = open('neg.'+ str(i)+ '.count.txt', 'r',encoding='utf-8')
    num = inputs.readlines()

    import re
    num = re.findall(r'\w{2}',num[1])
    num = int(num[0])
    sum_list = sum_list + num

In [5]:
sum_list

389

In [6]:
# -*-coding:utf-8-*-
from collections import Counter  
import jieba
import pandas as pd
from pandas import DataFrame

def count_words(i):
    with open('neg.'+str(i)+'.withoutstop.txt', 'r',encoding='utf-8') as fr: #读入已经去除停用词的文件  
        data = jieba.cut(fr.read())  
        data = dict(Counter(data))
        data.pop(' ')
        return data

frames = []
for i in range(11):
    data = count_words(i)
    print (data)
    df = DataFrame(data, index = [i])
    frames.append(df)
    
result=pd.concat(frames)

{'标准间': 2, '太': 1, '差': 1, '房间': 1, '星': 1, '设施': 1, '陈旧': 1, '建议': 1, '酒店': 1, '新': 1, '改善': 1}
{'服务态度': 1, '差': 2, '前台': 1, '接待': 2, '好象': 1, '受过': 1, '培训': 1, '礼貌': 1, '懂': 1, '几个': 1, '客人': 2, '大堂': 1, '副理': 1, '辩解': 1, '没完': 1, '总经理': 1, '电话': 1, '投诉': 1, '不敢': 1, '作': 1, '亏心事': 1, '情': 1, '根本': 1, '不用': 1}
{'好久': 1, '想': 1, '评价': 1, '记得': 1, '火车站': 1, '超级': 1, '方便': 1, '必然': 1, '觉得': 1, '比较': 1, '吵': 1, '韩日': 1, '旅游团': 1, '住': 1, '前台': 1, '服务': 1, '冷淡': 1, '两个': 1, '人住': 1, '标准间': 1, '只': 1, '一张': 1, '房卡': 1, '挑衅': 1, '气': 1, '心情': 1, '宾馆': 1, '反馈': 1, '2008': 1, '年': 1, '月': 1, '17': 1, '日': 1, '酒店': 2, '针对': 1, '客人': 1, '提出': 1, '问题': 1, '现已': 1, '认真': 1, '整改': 1, '希望': 1, '一位': 1, '入住': 2, '渤海': 1, '明珠': 1, '高兴': 1, '满意': 1}
{'预订': 1, '标准间': 1, '拐角': 2, '房间': 3, '携程': 1, '订': 1, '间': 1, '很小': 1, '隔音': 1, '超差': 1, '冷': 2, '空调': 1, '不好': 1, '卫生间': 1, '没法': 1, '淋浴': 1, '三个': 1, '字': 1, '满意': 1}
{'好久': 1, '想': 1, '评价': 1, '记得': 1, '火车站': 1, '超级': 1, '方便': 1, '必然': 1, '觉得': 1, '比较'

F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False



In [7]:
result

17  2008   24   27   29   QQ    一   一下   一个   一位 ...     间   附近   陈旧  \
0   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  1.0   
1   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
2   1.0   1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  NaN  NaN   
3   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN   
4   1.0   1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0 ...   NaN  NaN  NaN   
5   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN   
6   NaN   NaN  NaN  1.0  1.0  NaN  NaN  NaN  NaN  NaN ...   NaN  1.0  NaN   
7   NaN   NaN  NaN  1.0  1.0  NaN  NaN  NaN  NaN  NaN ...   NaN  1.0  NaN   
8   NaN   NaN  1.0  NaN  NaN  1.0  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
9   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   1.0  NaN  NaN   
10  NaN   NaN  NaN  NaN  NaN  NaN  1.0  1.0  1.0  NaN ...   NaN  NaN  NaN   

     隔壁   隔音   集团   韩日   预订   高兴    黑  
0   NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1   NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2   NaN  NaN  NaN  1.0  NaN  1.0  NaN  
3   NaN  1.0  NaN  NaN  1.0  NaN  NaN  
4   NaN  NaN  NaN  1.0  NaN  1.0  NaN  
5   NaN  1.0  NaN  NaN  1.0  NaN  NaN  
6   NaN  NaN  NaN  NaN  NaN  NaN  NaN  
7   NaN  NaN  NaN  NaN  NaN  NaN  NaN  
8   1.0  NaN  NaN  NaN  NaN  NaN  NaN  
9   NaN  NaN  NaN  NaN  NaN  NaN  1.0  
10  NaN  NaN  1.0  NaN  NaN  NaN  NaN  

[11 rows x 203 columns]

In [8]:
result.fillna(0, inplace=True)

In [9]:
result

17  2008   24   27   29   QQ    一   一下   一个   一位 ...     间   附近   陈旧  \
0   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  1.0   
1   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2   1.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0   
3   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  0.0   
4   1.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0   
5   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  0.0   
6   0.0   0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  0.0   
7   0.0   0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  0.0   
8   0.0   0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
9   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  0.0   
10  0.0   0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0 ...   0.0  0.0  0.0   

     隔壁   隔音   集团   韩日   预订   高兴    黑  
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2   0.0  0.0  0.0  1.0  0.0  1.0  0.0  
3   0.0  1.0  0.0  0.0  1.0  0.0  0.0  
4   0.0  0.0  0.0  1.0  0.0  1.0  0.0  
5   0.0  1.0  0.0  0.0  1.0  0.0  0.0  
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
8   1.0  0.0  0.0  0.0  0.0  0.0  0.0  
9   0.0  0.0  0.0  0.0  0.0  0.0  1.0  
10  0.0  0.0  1.0  0.0  0.0  0.0  0.0  

[11 rows x 203 columns]

In [10]:
def num_divided(x):
    return x/389

#应用列:
result = result.apply(num_divided, axis=0)

In [11]:
result

17      2008        24        27        29        QQ         一  \
0   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.002571  0.002571  0.000000  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4   0.002571  0.002571  0.000000  0.000000  0.000000  0.000000  0.000000   
5   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  0.002571  0.002571  0.000000  0.000000   
7   0.000000  0.000000  0.000000  0.002571  0.002571  0.000000  0.000000   
8   0.000000  0.000000  0.002571  0.000000  0.000000  0.002571  0.000000   
9   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.002571   

          一下        一个        一位    ...            间        附近        陈旧  \
0   0.000000  0.000000  0.000000    ...     0.000000  0.000000  0.002571   
1   0.000000  0.000000  0.000000    ...     0.000000  0.000000  0.000000   
2   0.000000  0.000000  0.002571    ...     0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.000000    ...     0.002571  0.000000  0.000000   
4   0.000000  0.000000  0.002571    ...     0.000000  0.000000  0.000000   
5   0.000000  0.000000  0.000000    ...     0.002571  0.000000  0.000000   
6   0.000000  0.000000  0.000000    ...     0.000000  0.002571  0.000000   
7   0.000000  0.000000  0.000000    ...     0.000000  0.002571  0.000000   
8   0.000000  0.000000  0.000000    ...     0.000000  0.000000  0.000000   
9   0.000000  0.000000  0.000000    ...     0.002571  0.000000  0.000000   
10  0.002571  0.002571  0.000000    ...     0.000000  0.000000  0.000000   

          隔壁        隔音        集团        韩日        预订        高兴         黑  
0   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
2   0.000000  0.000000  0.000000  0.002571  0.000000  0.002571  0.000000  
3   0.000000  0.002571  0.000000  0.000000  0.002571  0.000000  0.000000  
4   0.000000  0.000000  0.000000  0.002571  0.000000  0.002571  0.000000  
5   0.000000  0.002571  0.000000  0.000000  0.002571  0.000000  0.000000  
6   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
7   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
8   0.002571  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
9   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.002571  
10  0.000000  0.000000  0.002571  0.000000  0.000000  0.000000  0.000000  

[11 rows x 203 columns]

In [12]:
result.as_matrix()

F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00257069, 0.00257069, 0.        , ..., 0.        , 0.00257069,
        0.        ],
       ...,
       [0.        , 0.        , 0.00257069, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00257069],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [13]:
from sklearn import preprocessing
import numpy as np

result_scaled = preprocessing.scale(result)
result_scaled

array([[-0.47140452, -0.47140452, -0.31622777, ..., -0.47140452,
        -0.47140452, -0.31622777],
       [-0.47140452, -0.47140452, -0.31622777, ..., -0.47140452,
        -0.47140452, -0.31622777],
       [ 2.12132034,  2.12132034, -0.31622777, ..., -0.47140452,
         2.12132034, -0.31622777],
       ...,
       [-0.47140452, -0.47140452,  3.16227766, ..., -0.47140452,
        -0.47140452, -0.31622777],
       [-0.47140452, -0.47140452, -0.31622777, ..., -0.47140452,
        -0.47140452,  3.16227766],
       [-0.47140452, -0.47140452, -0.31622777, ..., -0.47140452,
        -0.47140452, -0.31622777]])

In [14]:
len(result_scaled[0])

203

In [15]:
min_max_scaler = preprocessing.MinMaxScaler()
result_train_minmax = min_max_scaler.fit_transform(result)
result_train_minmax

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
len(result_train_minmax[0])

203

In [17]:
result_normalized = preprocessing.normalize(result, norm='l2')
result_normalized

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.13608276, 0.13608276, 0.        , ..., 0.        , 0.13608276,
        0.        ],
       ...,
       [0.        , 0.        , 0.10206207, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.21320072],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [18]:
len(result_normalized[0])

203